### ISSUE TITLE
[Bug]: JEI plugin error during startup

### ISSUE THREAD

**Issue by lonevox** [GreateBeyondTheHorizon/Greate#23]
### Minecraft Version

1.20.1

### Modloader

Forge

### Modloader Version

47.2.17

### Greate Version

0.0.14

### What happened?

JEI plugin error during startup

### Log/Crash Report

[05:07:49] [Render thread/ERROR] [me.je.li.lo.PluginCaller/]: Caught an error from mod plugin: class electrolyte.greate.compat.jei.GreateJEI greate:jei_plugin
java.lang.ClassCastException: class net.minecraftforge.common.crafting.IntersectionIngredient cannot be cast to class com.gregtechceu.gtceu.api.recipe.ingredient.SizedIngredient (net.minecraftforge.common.crafting.IntersectionIngredient is in module forge@47.2.17 of loader 'TRANSFORMER' @526f6427; com.gregtechceu.gtceu.api.recipe.ingredient.SizedIngredient is in module gtceu@1.1.2.a of loader 'TRANSFORMER' @526f6427)
	at electrolyte.greate.content.processing.recipe.TieredProcessingRecipeBuilder.withItemIngredientsGT(TieredProcessingRecipeBuilder.java:64) ~[greate-0.0.14.jar%23289!/:0.0.14] {re:classloading}
	at electrolyte.greate.content.kinetics.millstone.TieredMillingRecipe.convertGT(TieredMillingRecipe.java:43) ~[greate-0.0.14.jar%23289!/:0.0.14] {re:classloading}
	at electrolyte.greate.compat.jei.GreateJEI.lambda$loadCategories$0(GreateJEI.java:91) ~[greate-0.0.14.jar%23289!/:0.0.14] {re:classloading}
	at electrolyte.greate.compat.jei.GreateJEI$CategoryBuilder.lambda$addTypedRecipesGT$10(GreateJEI.java:410) ~[greate-0.0.14.jar%23289!/:0.0.14] {re:classloading}
	at electrolyte.greate.compat.jei.GreateJEI.lambda$consumeTypedRecipes$21(GreateJEI.java:523) ~[greate-0.0.14.jar%23289!/:0.0.14] {re:classloading}
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?] {}
	at electrolyte.greate.compat.jei.GreateJEI.consumeTypedRecipes(GreateJEI.java:523) ~[greate-0.0.14.jar%23289!/:0.0.14] {re:classloading}
	at electrolyte.greate.compat.jei.GreateJEI$CategoryBuilder.lambda$addTypedRecipesGT$11(GreateJEI.java:410) ~[greate-0.0.14.jar%23289!/:0.0.14] {re:classloading}
	at electrolyte.greate.compat.jei.GreateJEI$CategoryBuilder.lambda$build$24(GreateJEI.java:499) ~[greate-0.0.14.jar%23289!/:0.0.14] {re:classloading}
	at electrolyte.greate.compat.jei.category.GreateRecipeCategory.registerRecipes(GreateRecipeCategory.java:81) ~[greate-0.0.14.jar%23289!/:0.0.14] {re:classloading}
	at electrolyte.greate.compat.jei.GreateJEI.lambda$registerRecipes$19(GreateJEI.java:325) ~[greate-0.0.14.jar%23289!/:0.0.14] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at electrolyte.greate.compat.jei.GreateJEI.registerRecipes(GreateJEI.java:325) ~[greate-0.0.14.jar%23289!/:0.0.14] {re:classloading}
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$10(PluginLoader.java:144) ~[jei-1.20.1-forge-15.2.0.27.jar%23295!/:15.2.0.27] {re:classloading}
	at mezz.jei.library.load.PluginCaller.redirect$ccg000$callOnPlugins(PluginCaller.java:541) ~[jei-1.20.1-forge-15.2.0.27.jar%23295!/:15.2.0.27] {re:mixin,re:classloading,pl:mixin:APP:emi.mixins.json:jei.PluginCallerMixin,pl:mixin:A}
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-forge-15.2.0.27.jar%23295!/:15.2.0.27] {re:mixin,re:classloading,pl:mixin:APP:emi.mixins.json:jei.PluginCallerMixin,pl:mixin:A}
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:144) ~[jei-1.20.1-forge-15.2.0.27.jar%23295!/:15.2.0.27] {re:classloading}
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-forge-15.2.0.27.jar%23295!/:15.2.0.27] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.20.1-forge-15.2.0.27.jar%23295!/:15.2.0.27] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.20.1-forge-15.2.0.27.jar%23295!/:15.2.0.27] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftMixin,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin,pl:mixin:APP:configuration.mixins.json:MinecraftMixin,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:prometheus-common.mixins.json:client.accessors.MinecraftAccessor,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftMixin,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin,pl:mixin:APP:configuration.mixins.json:MinecraftMixin,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:prometheus-common.mixins.json:client.accessors.MinecraftAccessor,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[?:?] {}

**Comment by Electrolyte220** [comment]
Downgrade GT to 1.1.1 for now.
